version: '3.8'

services:
  airflow:
    build:
      context: /workspaces/Data_Engineer_CamiloLyons
      dockerfile: Dockerfile
    command:
      - airflow
      - scheduler
    depends_on:
      redshift:
        condition: service_started
        required: true
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@redshift:5432/data-engineer-database
    image: airflow_redshift
    networks:
      default:
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
    volumes:
      - type: bind
        source: /workspaces/Data_Engineer_CamiloLyons/dags
        target: /usr/local/airflow/dags
        bind:
          create_host_path: true
      - type: bind
        source: /workspaces/Data_Engineer_CamiloLyons/logs
        target: /usr/local/airflow/logs
        bind:
          create_host_path: true
      - type: bind
        source: /workspaces/Data_Engineer_CamiloLyons/plugins
        target: /usr/local/airflow/plugins
        bind:
          create_host_path: true

  redshift:
    environment:
      POSTGRES_DB: data-engineer-database
      POSTGRES_PASSWORD: cC03egF87w
      POSTGRES_USER: camilo_lyv_coderhouse
    image: postgres:12
    networks:
      default:
    ports:
      - mode: ingress
        target: 5432
        published: "5432"
        protocol: tcp
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data

  webserver:
    build:
      context: /workspaces/Data_Engineer_CamiloLyons
      dockerfile: Dockerfile
    command:
      - airflow
      - webserver
    depends_on:
      airflow:
        condition: service_started
        required: true
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@redshift:5432/data-engineer-database
    image: airflow_redshift
    networks:
      default:
    ports:
      - mode: ingress
        target: 8080
        published: "8081"
        protocol: tcp
    volumes:
      - type: bind
        source: /workspaces/Data_Engineer_CamiloLyons/dags
        target: /usr/local/airflow/dags
        bind:
          create_host_path: true
      - type: bind
        source: /workspaces/Data_Engineer_CamiloLyons/logs
        target: /usr/local/airflow/logs
        bind:
          create_host_path: true
      - type: bind
        source: /workspaces/Data_Engineer_CamiloLyons/plugins
        target: /usr/local/airflow/plugins

networks:
  default:
    name: data_engineer_camilolyons_default

volumes:
  postgres-data:
    name: data_engineer_camilolyons_postgres-data
