version: '3.8'
services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "airflow db init &&
               airflow scheduler & 
               airflow webserver"
    depends_on:
      - redshift
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@redshift:5432/data-engineer-database
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs:/usr/local/airflow/logs
      - ./plugins:/usr/local/airflow/plugins

  redshift:
    image: postgres:12
    environment:
      POSTGRES_DB: data-engineer-database
      POSTGRES_USER: camilo_lyv_coderhouse
      POSTGRES_PASSWORD: cC03egF87w
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
