version: '3.9'

services:
  airflow:
    image: airflow_redshift
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs:/usr/local/airflow/logs
      - ./plugins:/usr/local/airflow/plugins
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@redshift:5432/data-engineer-database
    command: ["airflow", "scheduler"]
    depends_on:
      - redshift

  webserver:
    image: airflow_redshift
    build: .
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs:/usr/local/airflow/logs
      - ./plugins:/usr/local/airflow/plugins
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@redshift:5432/data-engineer-database
    command: ["airflow", "webserver"]
    depends_on:
      - airflow

  redshift:
    image: postgres:12
    environment:
      POSTGRES_USER: camilo_lyv_coderhouse
      POSTGRES_PASSWORD: cC03egF87w
      POSTGRES_DB: data-engineer-database
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
