version: '3.8'

services:
  airflow:
    image: airflow_redshift
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/usr/local/airflow/dags
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: ["airflow", "scheduler"]

  webserver:
    image: airflow_redshift
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    command: ["airflow", "webserver"]

  redshift:
    image: postgres:12
    environment:
      POSTGRES_USER: camilo_lyv_coderhouse
      POSTGRES_PASSWORD: cC03egF87w
      POSTGRES_DB: data-engineer-database
    ports:
      - "5439:5432"