name: data_engineer_camilolyons
services:
  airflow:
    build:
      context: /workspaces/Data_Engineer_CamiloLyons
      dockerfile: Dockerfile
    command:
      - airflow
      - scheduler
    depends_on:
      redshift:
        condition: service_started
        required: true
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@redshift:5432/data-engineer-database
    image: airflow_redshift
    ports:
      - "8080:8080"
    volumes:
      - /workspaces/Data_Engineer_CamiloLyons/dags:/usr/local/airflow/dags
      - /workspaces/Data_Engineer_CamiloLyons/logs:/usr/local/airflow/logs

  redshift:
    environment:
      - POSTGRES_DB=data-engineer-database
      - POSTGRES_PASSWORD=cC03egF87w
      - POSTGRES_USER=camilo_lyv_coderhouse
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  webserver:
    build:
      context: /workspaces/Data_Engineer_CamiloLyons
      dockerfile: Dockerfile
    command:
      - airflow
      - webserver
    depends_on:
      airflow:
        condition: service_started
        required: true
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@redshift:5432/data-engineer-database
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8080
    image: airflow_redshift
    ports:
      - "8081:8080"
    volumes:
      - /workspaces/Data_Engineer_CamiloLyons/dags:/usr/local/airflow/dags
      - /workspaces/Data_Engineer_CamiloLyons/logs:/usr/local/airflow/logs

networks:
  default:
    name: data_engineer_camilolyons_default

volumes:
  postgres-data:
    name: data_engineer_camilolyons_postgres-data

